json.id               realstate.id
json.name             realstate.name
json.category         realstate.category
json.street           realstate.street
json.external_number  realstate.external_number
json.internal_number  realstate.internal_number
json.neighborhood     realstate.neighborhood
json.city             realstate.city
json.country          realstate.country
json.rooms            realstate.rooms
json.bathrooms        realstate.bathrooms
json.comments         realstate.comments
